### ISSUE TITLE
Error on Raspberry PI 4 after install your setup guide

### ISSUE THREAD

**Issue by ChR-iSz** [seengreat/Motor-And-Servo-Driver-HAT#1]
With your demo code example, i get follow error:

`root@raspberrypi:/tmp/Motor-And-Servo-Driver-HAT/raspberry pi/python# python3 pca9685.py 
Traceback (most recent call last):
  File "/tmp/Motor-And-Servo-Driver-HAT/raspberry pi/python/pca9685.py", line 95, in <module>
    pwm = PCA9685()
  File "/tmp/Motor-And-Servo-Driver-HAT/raspberry pi/python/pca9685.py", line 41, in __init__
    self.write_reg(MODE1, 0x00)
  File "/tmp/Motor-And-Servo-Driver-HAT/raspberry pi/python/pca9685.py", line 44, in write_reg
    self.i2c.write_byte_data(self.dev_addr, reg, value)
OSError: [Errno 121] Remote I/O error`

**Comment by darkharasho** [comment]
Any chance you solved this issue? I am running into the same thing.

**Comment by seengreat** [comment]
1. Please turn all the bits on the I2C address setting switch to the "1" position, and then use the "i2cdetect -y -a 1" command to detect the address of the PCA9685 chip, and the result will be "7f";
2. Change the address of line 40 of the pca9685.py file to "self.dev_addr = 0x7f";
I am very sorry that this version of the code was used for testing at the time and was not modified.
